twig:
    file_name_pattern: '*.twig'
    form_themes: ['form/dsfr.html.twig']
    globals:
        app_env: '%env(APP_ENV)%'
        app_name: 'Vote en ligne' 
        app_tagline: 'COMGENDGP'
        app_slug: 'Le syst√®me de vote en ligne du COMGENDGP'

when@test:
    twig:
        strict_variables: true
